/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as MatchRouteImport } from './routes/match'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiChatIndexRouteImport } from './routes/ai.chat.index'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatIndexRoute = AiChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/rating': typeof RatingRoute
  '/shop': typeof ShopRoute
  '/teams': typeof TeamsRoute
  '/api/chat': typeof ApiChatRoute
  '/ai/': typeof AiIndexRoute
  '/ai/chat/': typeof AiChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/rating': typeof RatingRoute
  '/shop': typeof ShopRoute
  '/teams': typeof TeamsRoute
  '/api/chat': typeof ApiChatRoute
  '/ai': typeof AiIndexRoute
  '/ai/chat': typeof AiChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/rating': typeof RatingRoute
  '/shop': typeof ShopRoute
  '/teams': typeof TeamsRoute
  '/api/chat': typeof ApiChatRoute
  '/ai/': typeof AiIndexRoute
  '/ai/chat/': typeof AiChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/match'
    | '/rating'
    | '/shop'
    | '/teams'
    | '/api/chat'
    | '/ai/'
    | '/ai/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/match'
    | '/rating'
    | '/shop'
    | '/teams'
    | '/api/chat'
    | '/ai'
    | '/ai/chat'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/match'
    | '/rating'
    | '/shop'
    | '/teams'
    | '/api/chat'
    | '/ai/'
    | '/ai/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  AuthRoute: typeof AuthRoute
  MatchRoute: typeof MatchRoute
  RatingRoute: typeof RatingRoute
  ShopRoute: typeof ShopRoute
  TeamsRoute: typeof TeamsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat/': {
      id: '/ai/chat/'
      path: '/chat'
      fullPath: '/ai/chat/'
      preLoaderRoute: typeof AiChatIndexRouteImport
      parentRoute: typeof AiRoute
    }
  }
}

interface AiRouteChildren {
  AiIndexRoute: typeof AiIndexRoute
  AiChatIndexRoute: typeof AiChatIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiIndexRoute: AiIndexRoute,
  AiChatIndexRoute: AiChatIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  AuthRoute: AuthRoute,
  MatchRoute: MatchRoute,
  RatingRoute: RatingRoute,
  ShopRoute: ShopRoute,
  TeamsRoute: TeamsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
